In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv("Train.csv")

In [3]:
df

ID  Gender Ever_Married  Age Graduated     Profession  \
0     462809    Male           No   22        No     Healthcare   
1     462643  Female          Yes   38       Yes       Engineer   
2     466315  Female          Yes   67       Yes       Engineer   
3     461735    Male          Yes   67       Yes         Lawyer   
4     462669  Female          Yes   40       Yes  Entertainment   
...      ...     ...          ...  ...       ...            ...   
8063  464018    Male           No   22        No            NaN   
8064  464685    Male           No   35        No      Executive   
8065  465406  Female           No   33       Yes     Healthcare   
8066  467299  Female           No   27       Yes     Healthcare   
8067  461879    Male          Yes   37       Yes      Executive   

      Work_Experience Spending_Score  Family_Size  Var_1 Segmentation  
0                 1.0            Low          4.0  Cat_4            D  
1                 NaN        Average          3.0  Cat_4            A  
2                 1.0            Low          1.0  Cat_6            B  
3                 0.0           High          2.0  Cat_6            B  
4                 NaN           High          6.0  Cat_6            A  
...               ...            ...          ...    ...          ...  
8063              0.0            Low          7.0  Cat_1            D  
8064              3.0            Low          4.0  Cat_4            D  
8065              1.0            Low          1.0  Cat_6            D  
8066              1.0            Low          4.0  Cat_6            B  
8067              0.0        Average          3.0  Cat_4            B  

[8068 rows x 11 columns]

In [4]:
df = df.dropna()

In [5]:
df

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0     462809    Male           No   22        No  Healthcare              1.0   
2     466315  Female          Yes   67       Yes    Engineer              1.0   
3     461735    Male          Yes   67       Yes      Lawyer              0.0   
5     461319    Male          Yes   56        No      Artist              0.0   
6     460156    Male           No   32       Yes  Healthcare              1.0   
...      ...     ...          ...  ...       ...         ...              ...   
8062  463002    Male          Yes   41       Yes      Artist              0.0   
8064  464685    Male           No   35        No   Executive              3.0   
8065  465406  Female           No   33       Yes  Healthcare              1.0   
8066  467299  Female           No   27       Yes  Healthcare              1.0   
8067  461879    Male          Yes   37       Yes   Executive              0.0   

     Spending_Score  Family_Size  Var_1 Segmentation  
0               Low          4.0  Cat_4            D  
2               Low          1.0  Cat_6            B  
3              High          2.0  Cat_6            B  
5           Average          2.0  Cat_6            C  
6               Low          3.0  Cat_6            C  
...             ...          ...    ...          ...  
8062           High          5.0  Cat_6            B  
8064            Low          4.0  Cat_4            D  
8065            Low          1.0  Cat_6            D  
8066            Low          4.0  Cat_6            B  
8067        Average          3.0  Cat_4            B  

[6665 rows x 11 columns]

In [6]:
X = df.drop(columns=['ID', 'Var_1', "Segmentation"])
y = df['Segmentation']

In [7]:
X.isnull().sum()

Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
dtype: int64

In [8]:
y.isnull().sum()

np.int64(0)

In [9]:
X

Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0       Male           No   22        No  Healthcare              1.0   
2     Female          Yes   67       Yes    Engineer              1.0   
3       Male          Yes   67       Yes      Lawyer              0.0   
5       Male          Yes   56        No      Artist              0.0   
6       Male           No   32       Yes  Healthcare              1.0   
...      ...          ...  ...       ...         ...              ...   
8062    Male          Yes   41       Yes      Artist              0.0   
8064    Male           No   35        No   Executive              3.0   
8065  Female           No   33       Yes  Healthcare              1.0   
8066  Female           No   27       Yes  Healthcare              1.0   
8067    Male          Yes   37       Yes   Executive              0.0   

     Spending_Score  Family_Size  
0               Low          4.0  
2               Low          1.0  
3              High          2.0  
5           Average          2.0  
6               Low          3.0  
...             ...          ...  
8062           High          5.0  
8064            Low          4.0  
8065            Low          1.0  
8066            Low          4.0  
8067        Average          3.0  

[6665 rows x 8 columns]

In [10]:
y

0       D
2       B
3       B
5       C
6       C
       ..
8062    B
8064    D
8065    D
8066    B
8067    B
Name: Segmentation, Length: 6665, dtype: object

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,3,4,6])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
ct.get_feature_names_out()

array(['encoder__Gender_Female', 'encoder__Gender_Male',
       'encoder__Ever_Married_No', 'encoder__Ever_Married_Yes',
       'encoder__Graduated_No', 'encoder__Graduated_Yes',
       'encoder__Profession_Artist', 'encoder__Profession_Doctor',
       'encoder__Profession_Engineer',
       'encoder__Profession_Entertainment',
       'encoder__Profession_Executive', 'encoder__Profession_Healthcare',
       'encoder__Profession_Homemaker', 'encoder__Profession_Lawyer',
       'encoder__Profession_Marketing', 'encoder__Spending_Score_Average',
       'encoder__Spending_Score_High', 'encoder__Spending_Score_Low',
       'remainder__Age', 'remainder__Work_Experience',
       'remainder__Family_Size'], dtype=object)

In [13]:
X

array([[ 0.,  1.,  1., ..., 22.,  1.,  4.],
       [ 1.,  0.,  0., ..., 67.,  1.,  1.],
       [ 0.,  1.,  0., ..., 67.,  0.,  2.],
       ...,
       [ 1.,  0.,  1., ..., 33.,  1.,  1.],
       [ 1.,  0.,  1., ..., 27.,  1.,  4.],
       [ 0.,  1.,  0., ..., 37.,  0.,  3.]], shape=(6665, 21))

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
sc_x = MinMaxScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [16]:
X_train

array([[0.        , 1.        , 0.        , ..., 0.33802817, 0.07142857,
        0.125     ],
       [1.        , 0.        , 1.        , ..., 0.43661972, 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.32394366, 0.        ,
        0.125     ],
       ...,
       [0.        , 1.        , 0.        , ..., 0.63380282, 0.        ,
        0.375     ],
       [0.        , 1.        , 0.        , ..., 0.54929577, 0.        ,
        0.125     ],
       [1.        , 0.        , 1.        , ..., 0.11267606, 0.57142857,
        0.        ]], shape=(5332, 21))

In [17]:
from sklearn import svm
classifier = svm.SVC(kernel='rbf', random_state=42)
classifier.fit(X_train, y_train)

SVC(random_state=42)

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
y_test

288     D
2747    C
7472    D
3115    A
6651    A
       ..
429     A
6238    C
1296    C
2872    B
168     B
Name: Segmentation, Length: 1333, dtype: object

In [20]:
y_pred

array(['D', 'A', 'D', ..., 'C', 'C', 'C'], shape=(1333,), dtype=object)

In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5033758439609902
Classification Report:
               precision    recall  f1-score   support

           A       0.41      0.47      0.44       315
           B       0.33      0.29      0.31       302
           C       0.57      0.54      0.56       346
           D       0.66      0.66      0.66       370

    accuracy                           0.50      1333
   macro avg       0.49      0.49      0.49      1333
weighted avg       0.50      0.50      0.50      1333

Confusion Matrix:
 [[149  70  35  61]
 [ 91  88  97  26]
 [ 50  67 188  41]
 [ 74  40  10 246]]


In [22]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression()
log_model.fit(X_train, y_train)

LogisticRegression()

In [23]:
y_pred_log = log_model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Classification Report:\n", classification_report(y_test, y_pred_log))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))

Accuracy: 0.5221305326331583
Classification Report:
               precision    recall  f1-score   support

           A       0.43      0.52      0.47       315
           B       0.41      0.24      0.30       302
           C       0.52      0.62      0.57       346
           D       0.66      0.67      0.67       370

    accuracy                           0.52      1333
   macro avg       0.51      0.51      0.50      1333
weighted avg       0.52      0.52      0.51      1333

Confusion Matrix:
 [[163  40  55  57]
 [ 82  71 123  26]
 [ 49  40 215  42]
 [ 83  23  17 247]]


In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print("KNN Classification Report:\n", classification_report(y_test, y_pred_knn))

KNN Accuracy: 0.47861965491372843
KNN Classification Report:
               precision    recall  f1-score   support

           A       0.37      0.46      0.41       315
           B       0.36      0.36      0.36       302
           C       0.54      0.51      0.53       346
           D       0.66      0.56      0.60       370

    accuracy                           0.48      1333
   macro avg       0.48      0.47      0.48      1333
weighted avg       0.49      0.48      0.48      1333



In [26]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=500)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest Classification Report:\n", classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.4808702175543886
Random Forest Classification Report:
               precision    recall  f1-score   support

           A       0.40      0.42      0.41       315
           B       0.37      0.34      0.35       302
           C       0.51      0.52      0.51       346
           D       0.61      0.61      0.61       370

    accuracy                           0.48      1333
   macro avg       0.47      0.47      0.47      1333
weighted avg       0.48      0.48      0.48      1333



In [27]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Decision Tree Classification Report:\n", classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.45461365341335336
Decision Tree Classification Report:
               precision    recall  f1-score   support

           A       0.40      0.43      0.41       315
           B       0.34      0.35      0.35       302
           C       0.45      0.45      0.45       346
           D       0.62      0.56      0.59       370

    accuracy                           0.45      1333
   macro avg       0.45      0.45      0.45      1333
weighted avg       0.46      0.45      0.46      1333



In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.losses import SparseCategoricalCrossentropy


c:\Users\ramad\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\ramad\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\ramad\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framewo

In [29]:
def create_model(optimizer='adam', activation='relu'):
    model = Sequential()
    model.add(Dense(64, input_shape=(X_train.shape[1],), activation=activation))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(4, activation='softmax')) 
    model.compile(optimizer=optimizer,
                  loss=SparseCategoricalCrossentropy(),
                  metrics=['accuracy'])
    return model

In [ ]:

model = KerasClassifier(
    model=create_model,
    optimizer="adam",        
    activation="relu",       
    verbose=0
)


param_grid = {
    "optimizer": ["adam", "rmsprop"],       
    "activation": ["relu", "tanh"],         
    "batch_size": [32, 64],
    "epochs": [50, 150, 250]
}

In [33]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring="accuracy", verbose=1, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

print("Best Parameters:", grid_result.best_params_)
print("Best Score:", grid_result.best_score_)

Fitting 3 folds for each of 24 candidates, totalling 72 fits


c:\Users\ramad\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Best Parameters: {'activation': 'relu', 'batch_size': 64, 'epochs': 50, 'optimizer': 'rmsprop'}
Best Score: 0.5283207775730342


In [34]:
best_model = grid_result.best_estimator_

In [35]:
y_pred = best_model.predict(X_test)

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           A       0.44      0.40      0.42       315
           B       0.46      0.24      0.31       302
           C       0.51      0.70      0.59       346
           D       0.62      0.71      0.66       370

    accuracy                           0.53      1333
   macro avg       0.51      0.51      0.50      1333
weighted avg       0.51      0.53      0.51      1333

Confusion Matrix:
[[125  47  67  76]
 [ 60  71 137  34]
 [ 25  28 243  50]
 [ 71  10  25 264]]


In [37]:
from sklearn.metrics import accuracy_score

test_accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {test_accuracy:.4f}")

Test Accuracy: 0.5274
